### ISSUE TITLE
Deposit to Account

### ISSUE THREAD

**Issue by SilasReinagel** [SOOlutions/HomeTaskApp#2]
User should be able to to deposit an amount of currency at a specific point in time to his created account.
Account balance should be correct.

**Comment by vivekimsit** [comment]
Nouns: `Account`, `Currency`
Verbs: `Deposit`

**Comment by yohanmishkin** [comment]
Object: `Account`
Behavior: `Deposit(Currency)`

**Comment by goqp** [comment]
Object: Account
Message: Deposit(Currency)
 Behavior: Response to the message. Either do nothing, send a message, or do a computation.

**Comment by yohanmishkin** [comment]
We may have to tweak this slightly. I think maybe `Deposit(Amount)` might be more appropriate, where an `Amount` has some number value and a `Currency`.
